id: P010461
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:51:04.687622
source_metadata:
  id: bdr:W00KG09823
  title: དབོན་ཞང་རྡོ་རིང་དང་ཐང་བོད་བར་གྱི་འབྲེལ་བ་
  author: ''
  volumes:
    784976da74ce42e7bd332eb03bcb1c64:
      image_group_id: I00KG09863
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
